### ISSUE TITLE
Composition vs Inheritance

### ISSUE THREAD

**Issue by chrisjenx** [hotwired/turbo-android#133]
As we are working with pure Kotlin at this point, the multiple abstract classes makes it very difficult to work with out own classes forcing us to write our own delegates for dagger and and other logic.

Ideally things like TurboFragment, WebTurboFragment should be interfaces, if you want to provide a default implementation of those interfaces that would be fine, but now we have to have multiple base classes instead of the 1 we used to have.

**Comment by jayohms** [comment]
I agree that the abstract class setup it not ideal. It's born from the fact that Android's different fragment types are `Fragment` subclasses. Turbo currently supports `Fragment` and `BottomSheetDialogFragment` destinations (with future plans to support `DialogFragment` and possibly others). So, an application that takes advantage of Turbo's features would never be able to have a single base `Fragment` class.

Given this framework limitation, and since Turbo's navigation is heavily tied into the `Fragment` lifecycle, offering subclasses makes the most sense for the library.

To work around this, all Turbo fragment destinations implement the [`TurboNavDestination` interface](https://github.com/hotwired/turbo-android/blob/main/turbo/src/main/kotlin/dev/hotwire/turbo/nav/TurboNavDestination.kt). You can extend this interface and drop in the common functionality that your Fragment destinations use there. And example is provided in the demo app with the [`NavDestination` interface](https://github.com/hotwired/turbo-android/blob/main/demo/src/main/kotlin/dev/hotwire/turbo/demo/base/NavDestination.kt) and used [here](https://github.com/hotwired/turbo-android/blob/main/demo/src/main/kotlin/dev/hotwire/turbo/demo/features/web/WebFragment.kt#L12), [here](https://github.com/hotwired/turbo-android/blob/main/demo/src/main/kotlin/dev/hotwire/turbo/demo/features/numbers/NumbersFragment.kt#L16), and [here](https://github.com/hotwired/turbo-android/blob/main/demo/src/main/kotlin/dev/hotwire/turbo/demo/features/web/WebBottomSheetFragment.kt#L8)

I'll think about this more and see if there's an opportunity down the road to make the library more flexible, but it's not in the near-term plans to restructure the classes. Thanks for the feedback and hopefully the `TurboNavDestination` interface helps!
