### ISSUE TITLE
Default Back Button Behavior 

### ISSUE THREAD

**Issue by chrisjenx** [hotwired/turbo-android#135]
Not sure what should happen, but I was under the impression that device back button should pop fragments off the stack (default fragment manager behavior?). In testing seems like back button will not do that and just close the activity.
So I've overridden `onBackPressed` to fire navigateBack(). Just thought the NavHostFragments were meant to do this for you?

Wondering how you handle this on HEY and maybe we should add a note to the docs? If it should pop the navigation stack then there is potentially a bug somewhere which I'll try and investigate.

**Comment by jayohms** [comment]
This isn't the expected behavior. You'll see in the demo app that Fragments are properly popped off the backstack (it's a single-Activity app). So, this probably points to a bug in your app.

Are you initializing the `delegate` in your Activity? https://github.com/hotwired/turbo-android/blob/main/docs/QUICK-START.md#create-the-turboactivity-class

The library automatically adds an `OnBackPressedCallback` when creating the Activity `delegate`, which will pop Fragments off the backstack when using the system back button.

**Comment by chrisjenx** [comment]
Ahh yes, did some digging, was a race condition with dagger.
