### ISSUE TITLE
onShowFileChooser Camera Intent Support

### ISSUE THREAD

**Issue by chrisjenx** [hotwired/turbo-android#139]
Unless I'm missing something, I can't see any way to add/change File Upload intents, you default to using the `Intents.createChooser`.

What's the way/plan to support using the camera? (If it isn't already and I'm just missing it...)

**Comment by jayohms** [comment]
@chrisjenx It's not currently possible to change file upload intents, unless you override and handle [`TurboWebChromeClient. onShowFileChooser()`](https://github.com/hotwired/turbo-android/blob/main/turbo/src/main/kotlin/dev/hotwire/turbo/views/TurboWebChromeClient.kt#L10-L19) yourself, but this would add a lot of complexity. 

Adding camera capture support sounds like a good idea to me, especially since [`WebChromeClient` supports the `capture` attribute](https://developer.android.com/reference/android/webkit/WebChromeClient.FileChooserParams#isCaptureEnabled()). I should have some time this week to look at it, so I'll investigate how to make this more flexible and come up with a PR.

**Comment by chrisjenx** [comment]
Hey @jayohms, thanks for replying. How do you handle this on HEY btw?

**Comment by jayohms** [comment]
We currently don't offer camera capture in HEY, but we may offer it it's built into turbo-android :)

**Comment by jayohms** [comment]
Work in progress here: https://github.com/hotwired/turbo-android/pull/141

**Comment by jayohms** [comment]
Closing, since the work in #141 is complete. Camera intent support will be available in the upcoming `7.0.0-beta06` release.

**Comment by chrisjenx** [comment]
Wow, awesome, appreciate it!
