### ISSUE TITLE
Navigating to a different Activity with ReplaceRoot

### ISSUE THREAD

**Issue by chrisjenx** [hotwired/turbo-android#143]
When you navigate to a different activity using the internal navigation + replace_root, it doens't `finish` the activity you are coming from. Again not sure if thats correct or not, but my understanding of replace_root is like "NEWTASK/CLEARTASK"? Or at least that screen should be the start of the stack.

This most common when say LoginActivity -> MainTurboActivity when we have logged in and out states divided by an activity scope. And Visa versa, MainTurboActivity -> LoginActivity.

Thanks,
Chris

**Comment by chrisjenx** [comment]
I can of course override the shouldNavigate, but something tells me that replace_root should replace activities too, Or maybe adding another explicit `clear_stack`? or something?

**Comment by jayohms** [comment]
Yeah, you're correct, navigating to an `Activity` currently doesn't respect the `presentation` flags - sorry, that isn't documented anywhere at the moment. Currently, in that situation we simply do the following:

**`LoginActivity`**:
```kotlin
private fun navigateToMainActivity() {
    delegate.navigate(urls.activityMainUrl)
    finish()
}
```

I haven't put much thought into `presentation` flags for activities yet, simply because the primary use case is Fragment navigation and navigating between activities should be infrequently used. I agree that this could be a lot nicer - especially considering that the `presentation` flags can be changed remotely to change behavior without an app update. 

I'll think about this a bit more and figure out what makes sense. A limited subset, or separate `presentation` flags for activities might be best.

**Comment by chrisjenx** [comment]
yeah, I just added `finish()` on calling navigate(login) so no rush from over here. Just something to think about I guess. :+1:
