### ISSUE TITLE
How can I reassign TurboNavDestination#location ?

### ISSUE THREAD

**Issue by fffx** [hotwired/turbo-android#182]
I have a problem when a user change language and navigate back, I need to modify the URL before render.  since the language flag in the URL. 

For example:
When a user navigates to `/en/account`, then click on  `/zh-CN/account`, the language changed to Chinese, then user switchback, language changed to English again, to fix this I need to change  `TurboNavDestination#location`, replace `/en` with `/zh-CN`, but the `location` is declared by `val`, so I can't change it, is there another way to  fix it? Or could you change `val` to `var`? Thanks.

**Comment by jayohms** [comment]
The `location` is immutable for each destination and that can't change, based on the current architecture and navigation rules.

When navigating back to a destination, if you can detect the language change, you can perform a `replace` visit to replace the previous fragment destination with the new one:
```kotlin
navigate(".../zh-CN/path", TurboVisitOptions(action = TurboVisitAction.REPLACE))
```

Alternatively, you could consider clearing the backstack when changing languages, since I imagine changing the language is a pretty big change from a user's perspective:
```kotlin
clearBackStack()
```

**Comment by fffx** [comment]
Thanks, it helped a lot

**Comment by MichalSznajder** [comment]
@fffx Do you recall where did you put your code that executes `clearBackStack()` or `navigate()`?
