### ISSUE TITLE
Add `TurboSessionNavHostFragment` API documentation

### ISSUE THREAD

**Issue by jayohms** [hotwired/turbo-android#194]

**Comment by lanke96** [comment]
Hi there! I am trying to make a bottom navigation bar, and the application crashed when I add `app:navGraph="@navigation/nav_graph` to the  `FragmentContainerView`. The trace back takes me to some Turbo classes, so I assume that either Turbo is not compatible with the navgraph, or I am missing a configuration. I've been struggling with this for days, and I haven't come up with a solution. 
That happens when the MainActivity tries to inflate its layout `setContentView(R.layout.activity_main)`
![image](https://user-images.githubusercontent.com/18342337/136471806-ba5bb973-52d0-4ac6-a097-eadf81e341b9.png)

**Comment by tannakartikey** [comment]
> I'll write up an example of using bottom navigation tabs with turbo-android soon, but I won't have time in the next week. For some pointers, see the discussion here: https://github.com/hotwired/turbo-android/issues/189

Hey @jayohms 
Just wanted to know if you have written the example of using bottom navigation tabs. I could not find it on the repo.
Thanks for turbo-android! :)

**Comment by jayohms** [comment]
Missing API documentation added here: https://github.com/hotwired/turbo-android/pull/313
